---
# handlers file for ansible_role_microk8s

- name: Refresh certs
  become: yes
  shell: >
    rm -rf /var/snap/microk8s/current/var/lock/no-cert-reissue
    microk8s refresh-certs --cert server.crt
    sleep 5
    touch /var/snap/microk8s/current/var/lock/no-cert-reissue
